# Copyright (c) 2026 Madalin Gabriel Ignisca <hi@madalin.me>
# Copyright (c) 2026 Vlah Software House SRL <contact@vlah.sh>
# All rights reserved. See LICENSE for details.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yaaicms
spec:
  ingressClassName: traefik
  rules:
    - host: yaaicms.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: yaaicms
                port:
                  name: http
  tls:
    - hosts:
        - yaaicms.example.com
      secretName: yaaicms-tls
