apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartpress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - host: smartpress.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smartpress
                port:
                  name: http
  tls:
    - hosts:
        - smartpress.example.com
      secretName: smartpress-tls
