# Copyright (c) 2026 Madalin Gabriel Ignisca <hi@madalin.me>
# Copyright (c) 2026 Vlah Software House SRL <contact@vlah.sh>
# All rights reserved. See LICENSE for details.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: yaaicms

patches:
  - path: ingress-patch.yaml
  - path: deployment-patch.yaml

# To create the secrets from the .secrets file:
#   kubectl create secret generic yaaicms-secrets \
#     --from-env-file=../../.secrets \
#     -n yaaicms \
#     --dry-run=client -o yaml > secret.yaml
#
# Then add secret.yaml to resources (it is gitignored).
